In [4]:
import numpy as np
from qiskit import QuantumCircuit, Aer, transpile
from qiskit.visualization import plot_bloch_multivector
from qiskit.quantum_info import Statevector
from IPython.display import display
from qiskit.tools.visualization import plot_histogram

sim = Aer.get_backend("aer_simulator")

# Q7  Xゲートを行列表現せよ。同様に、Y, Z, H, S, T, Rx, Ry, Rzの各ゲートを行列表現せよ。



## 解答

In [1]:
import numpy as np
# Xゲート
from qiskit.circuit.library import XGate

x_matrix = np.array([[0,1],[1,0]])
# 行列の比較
if np.array_equal(XGate().to_matrix() , x_matrix):
    print('Xゲート:\n', x_matrix)

# Yゲート
from qiskit.circuit.library import YGate

y_matrix = np.array([[0,-1j],[1j,0]])
# 行列の比較
if np.array_equal(YGate().to_matrix() , y_matrix):
    print('Yゲート:\n',y_matrix)
    

# Zゲート
from qiskit.circuit.library import ZGate

z_matrix = np.array([[1,0],[0,-1]])
# 行列の比較
if np.array_equal(ZGate().to_matrix() , z_matrix):
    print('Zゲート:\n',z_matrix)

# Hゲート
from qiskit.circuit.library import HGate

h_matrix = np.array([[1/np.sqrt(2),1/np.sqrt(2)],[1/np.sqrt(2),-1/np.sqrt(2)]])
# 行列の比較
if np.array_equal(HGate().to_matrix() , h_matrix):
    print('Zゲート:\n',h_matrix)

# Sゲート
from qiskit.circuit.library import SGate
s_matrix = np.array([[1,0],[0,1j]])
# 行列の比較
if np.array_equal(SGate().to_matrix() , s_matrix):
    print('Sゲート:\n',s_matrix)

# S*ゲート
from qiskit.circuit.library import SdgGate

s_dg_matrix = np.array([[1,0],[0,-1j]])
# 行列の比較
if np.array_equal(SdgGate().to_matrix() , s_dg_matrix):
    print('S*ゲート:\n',s_dg_matrix)


# Tゲート
from qiskit.circuit.library import TGate

t_matrix = np.array([[1,0],[0,1/np.sqrt(2)+1j/np.sqrt(2)]])
# 行列の比較
if np.array_equal(TGate().to_matrix() , t_matrix):
    print('Tゲート:\n',t_matrix)

# T*ゲート
from qiskit.circuit.library import TdgGate

t_dg_matrix = np.array([[1,0],[0,1/np.sqrt(2)-1j/np.sqrt(2)]])
# 行列の比較
if np.array_equal(TdgGate().to_matrix() , t_dg_matrix):
    print('T*ゲート:\n',t_dg_matrix)
    
# RXゲート
from qiskit.circuit.library import RXGate

theta = np.pi/2
rx_matrix = np.array([[np.cos(theta/2), -1j*np.sin(theta/2)],[-1j*np.sin(theta/2),np.cos(theta/2)]])
# 行列の比較
if np.array_equal(RXGate(theta).to_matrix() , rx_matrix):
    print(f'RXゲート:theta = {theta}\n',rx_matrix)
    

# RYゲート
from qiskit.circuit.library import RYGate

theta = np.pi/2
ry_matrix = np.array([[np.cos(theta/2), -np.sin(theta/2)],[np.sin(theta/2),np.cos(theta/2)]])
# 行列の比較
if np.array_equal(RYGate(theta).to_matrix() , ry_matrix):
    print(f'RYゲート:theta = {theta}\n',ry_matrix)

# RZゲート
from qiskit.circuit.library import RZGate

theta = np.pi/2
rz_matrix = np.array([[np.exp(-1j*theta/2),0],[0 ,np.exp(1j*theta/2)]])
# 行列の比較
if np.array_equal(RZGate(theta).to_matrix() , rz_matrix):
    print(f'RZゲート:theta = {theta}\n',rz_matrix)

Xゲート:
 [[0 1]
 [1 0]]
Yゲート:
 [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
Zゲート:
 [[ 1  0]
 [ 0 -1]]
Zゲート:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
Sゲート:
 [[1.+0.j 0.+0.j]
 [0.+0.j 0.+1.j]]
S*ゲート:
 [[ 1.+0.j  0.+0.j]
 [ 0.+0.j -0.-1.j]]
Tゲート:
 [[1.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.70710678+0.70710678j]]
T*ゲート:
 [[1.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.70710678-0.70710678j]]
RXゲート:theta = 1.5707963267948966
 [[0.70710678+0.j         0.        -0.70710678j]
 [0.        -0.70710678j 0.70710678+0.j        ]]
RYゲート:theta = 1.5707963267948966
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
RZゲート:theta = 1.5707963267948966
 [[0.70710678-0.70710678j 0.        +0.j        ]
 [0.        +0.j         0.70710678+0.70710678j]]


## 解説
以下のゲート操作の行列をqiskitで表現する。

$$
{X = \left( \begin{array}{cc} 0 & 1\\ 1 & 0 \end{array} \right),
Y = \left( \begin{array}{cc} 0 & -i\\ i & 0 \end{array} \right),
Z = \left( \begin{array}{cc} 1 & 0\\ 0 & -1 \end{array} \right)\\
},
{H = \frac{1}{\sqrt2} \left( 
\begin{array}{cc} 1 & 1\\ 1 & -1 \end{array} \right)
}
$$
$$
{S = \left( \begin{array}{cc} 1 & 0\\ 0 & i \end{array} \right),
S^{\dagger} = \left( \begin{array}{cc} 1 & 0\\ 0 & -i \end{array} \right),
T = \left( \begin{array}{cc} 1 & 0\\ 0 & e^{i\frac{\pi}{4}} \end{array} \right),
T^{\dagger} = \left( \begin{array}{cc} 1 & 0\\ 0 & -e^{i\frac{\pi}{4}} \end{array} \right)
}
$$